[target.aarch64-linux-android]
linker = "C:\\Users\\Muhib\\AppData\\Local\\Android\\Sdk\\ndk\\28.0.13004108\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android28-clang.cmd"

[env]
CC_aarch64_linux_android = "C:\\Users\\Muhib\\AppData\\Local\\Android\\Sdk\\ndk\\28.0.13004108\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android28-clang.cmd"
CXX_aarch64_linux_android = "C:\\Users\\Muhib\\AppData\\Local\\Android\\Sdk\\ndk\\28.0.13004108\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android28-clang++.cmd"
AR_aarch64_linux_android = "C:\\Users\\Muhib\\AppData\\Local\\Android\\Sdk\\ndk\\28.0.13004108\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"
ANDROID_NDK_HOME = "C:\\Users\\Muhib\\AppData\\Local\\Android\\Sdk\\ndk\\28.0.13004108"
ANDROID_NDK = "C:\\Users\\Muhib\\AppData\\Local\\Android\\Sdk\\ndk\\28.0.13004108"
ORT_LIB_LOCATION = "C:\\Users\\Muhib\\Desktop\\VoiceAI\\VoiceAI-v1\\libs\\onnxruntime\\jni\\arm64-v8a"
ORT_INCLUDE_DIR = "C:\\Users\\Muhib\\Desktop\\VoiceAI\\VoiceAI-v1\\libs\\onnxruntime\\headers"

